[MIN-1597] Minswap syncer for query price for v1, v2 and stableswap pool.
minswap/sdk pull request #40
Opened 2024-09-17 11:29 UTC by hieupnh

2024-09-18 03:07 UTC, h2physics commented on src/types/tx.internal.ts
> +    for (const [cyrencySymbol, tokenNameMap] of Object.entries(ogmiosValue)) {
```suggestion
    for (const [currencySymbol, tokenNameMap] of Object.entries(ogmiosValue)) {
```

2024-09-23 10:13 UTC, longngn commented on package.json
> +    "@cardano-ogmios/schema": "^6.7.0",
need to be the same and similar to Ogmios in Docker files

2024-09-23 10:18 UTC, longngn requested changes

2024-09-23 10:18 UTC, longngn commented on package.json
> +    "@types/node": "^22.5.5",
should be 20.x.x (because we use node 20)

2024-09-23 10:18 UTC, longngn commented on src/syncer/repository/postgres-reposiotry.ts
> +import * as OgmiosSchema from "@cardano-ogmios/schema";
file name typo
reposiotry => repository

2024-09-23 10:20 UTC, longngn commented
Test import lib like this:

1. Create new node project
2. Import by local dir like this: `"@minswap/sdk": "local/path/to/sdk/build/dir"`
3. Test if we can import and use `@minswap/sdk` as a lib

2024-09-25 02:44 UTC, lednhatkhanh commented
@longngn @hieupnh I'm fixing this

2024-09-25 04:19 UTC, h2physics approved these changes

2024-09-25 04:19 UTC, merged