feat: Maestro adapter
minswap/sdk pull request #50
Opened 2024-12-15 23:36 UTC by Vardominator

* Abstracted `Adapter` interface
* Added `MaestroAdapter`, which implements `Adapter` interface
* Added example with `MaestroAdapter`
* Various helpers
* Various cleanup and formatting
* Updated README
* Updated tests

2025-01-03 06:04 UTC, longngn requested changes

2025-01-03 06:04 UTC, longngn commented on test/adapter.test.ts
> +async function runTests(adapterTestnet: any, adapterMainnet: any) {
type should be `Adapter` not `any`

2025-01-03 06:04 UTC, longngn commented on test/adapter.test.ts
> +  async function testPoolPrice(adapter: any): Promise<void> {
same as above

2025-01-03 06:04 UTC, longngn commented on package.json
> +    "@trivago/prettier-plugin-sort-imports": "^5.2.0",
why install this plugin but not used it anywhere

2025-01-03 06:04 UTC, longngn commented on examples/blockfrost-adapter-example.ts
> +import { BlockfrostAdapter } from "../src/adapters/blockfrost";
`src/adapters` should have `index.ts` file that export `Adapter` interface and the 3 adapters out
then `src/index.ts` should export the interface + 3 adapters as well
it makes sure lib consumers can `import { ... } from "@minswap/sdk"`

2025-01-03 07:58 UTC, longngn requested changes

2025-01-03 07:58 UTC, longngn commented on test/adapter.test.ts
> +  );
should use `mustGetEnv` like with Blockfrost above so we can run this in CI
also update `.github/workflows/ci.yml` to get env vars from Github secrets

2025-01-03 07:58 UTC, longngn commented on test/adapter.test.ts
> +  }
can you keep my comments here

2025-01-03 22:02 UTC, Vardominator commented on test/adapter.test.ts
> +  }
what are you referring to?

2025-01-03 22:03 UTC, Vardominator commented on examples/blockfrost-adapter-example.ts
> +import { BlockfrostAdapter } from "../src/adapters/blockfrost";
done

2025-01-03 22:03 UTC, Vardominator commented
@longngn thanks! I believe I have addressed everything but I don't understand the last comment.

2025-01-04 05:11 UTC, longngn commented on test/adapter.test.ts
> +  }
@Vardominator in the old code I have code comments to explain the formula :p (the `// blabla` parts)

2025-01-04 06:32 UTC, Vardominator commented
@longngn done with everything

2025-01-04 15:54 UTC, longngn commented
> @longngn done with everything

I've added the Maestro API keys to run CI
however it has error when `pnpm install` now
can you update pnpm lock file (I think just need to run `pnpm install` again)

2025-01-04 16:44 UTC, Vardominator commented
@longngn done

2025-01-06 09:51 UTC, longngn commented
> @longngn done

it seems CI can't fetch secrets from PR that is based from a fork
i've added you as collaborator to this repo, can you re-create a PR directly in this repo to use CI?

2025-01-07 01:50 UTC, closed without merging